<div class="navbar-default sidebar" role="navigation">
	<div class="sidebar-nav navbar-collapse">
		<ul class="nav" id="side-menu">
			<li class="sidebar-search">
				<div class="input-group custom-search-form">
					<input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
									<i class="fa fa-search"></i>
								</button>
                            </span>
				</div>
				<!-- /input-group -->
			</li>
			<li>
				<a href="/admin/"><i class="fa fa-dashboard fa-fw"></i> Tableau de bord</a>
			</li>
			<li>
				<a href="/admin/stable/"><i class="fa fa-table fa-fw"></i> Ecuries</a>
			</li>
			<li>
				<a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Chevaux<span class="fa arrow"></span></a>
				<ul class="nav nav-second-level">
					<li>
						<a href="/admin/horse/">Liste des chevaux</a>
					</li>
					<li>
						<a href="/admin/horse/createauto/">Générer à partir d'un étalon et une poulinière</a>
					</li>
				</ul>
				<!-- /.nav-second-level -->
			</li>
			<li>
				<a href="tables.html"><i class="fa fa-table fa-fw"></i> Courses<span class="fa arrow"></span></a>
				<ul class="nav nav-second-level">
					<li>
						<a href="/admin/race/indexTmp">Courses temporaires</a>
					</li>
					<li>
						<a href="/admin/race/">Courses officielles</a>
					</li>
					<li>
						<a href="/admin/race/hippo/">Hippodromes</a>
					</li>
					<li>
						<a href="/admin/race/category/">Catégories</a>
					</li>
					<li>
						<a href="/admin/race/type/">Types</a>
					</li>
					<li>
						<a href="/admin/race/piste/">Pistes</a>
					</li>
					<li>
						<a href="/admin/race/group/">Groupes</a>
					</li>
				</ul>
			</li>
		</ul>
	</div>
	<!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->