<div class="container">
	<div class="row">
		<div class="col-md-5">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Creer votre propre ecurie</h3>
				</div>
				<form role="form" action="/stable/create/" method="post">
					<div class="panel-body">
						<fieldset>
							<label>Information de votre ecurie</label>
							<div class="form-group">
								<input class="form-control" placeholder="Nom de l'ecurie" name="name" type="text" autofocus>
							</div>
							<div class="form-group">
								<select class="form-control" name="continent">
									<option value="">Continent</option>
									<option>Europe</option>
								</select>
							</div>
							<div class="form-group">
								<select class="form-control" name="country">
									<option value="">Pays</option>
									<option>France</option>
								</select>
							</div>
						</fieldset>
						<fieldset>
							<label>Information du proprietaire/entraineur/jockey</label>
							<div class="form-group">
								<input class="form-control" placeholder="Nom du proprietaire" name="firstname" type="text">
							</div>
							<div class="form-group">
								<input class="form-control" placeholder="Prenom du proprietaire" name="lastname" type="text">
							</div>
						</fieldset>
						<fieldset>
							<label>Information de connexion</label>
							<div class="form-group">
								<input class="form-control" placeholder="Email" name="email" type="email">
							</div>
							<div class="form-group">
								<input class="form-control" placeholder="Password" name="password" type="password" value="">
							</div>
							<!-- Change this to a button or input when using this as a form -->
							<button type="submit" class="btn btn-lg btn-success btn-block">Creer</button>
						</fieldset>
					</div>
				</form>
			</div>
		</div>
		<div class="col-md-5">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Please Sign In</h3>
				</div>
				<div class="panel-body">
					<form role="form" action="/index/connect" method="post">
						<fieldset>
							<div class="form-group">
								<input class="form-control" placeholder="Email" name="email" type="email" autofocus>
							</div>
							<div class="form-group">
								<input class="form-control" placeholder="Password" name="password" type="password" value="">
							</div>
							<div class="checkbox">
								<label>
									<input name="remember" type="checkbox" value="Remember Me">Remember Me
								</label>
							</div>
							<!-- Change this to a button or input when using this as a form -->
							<button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
