<!-- DataTables JavaScript -->
<script src="/themes/admin/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="/themes/admin/bootstrap/datatables/dataTables.bootstrap.min.js"></script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Les catégories</h1>
    </div>
    <!-- /.col-lg-12 -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-hippo">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nom</th>
                                <th>Groupe valide</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php  foreach($hippos as $hippo) { ?>
                                <tr class="">
                                    <td><?php echo $hippo['id'] ?></td>
                                    <td><?php echo $hippo['title'] ?></td>
                                    <td><?php echo $hippo['groups'] ?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>


<script>
    $(document).ready(function() {
        $('#dataTables-hippo').DataTable({
            responsive: true
        });
    });
</script>