<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Course :: modifier :: Nouveau</h1>

        <!-- /.col-lg-12 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Informations de l'écurie
            </div>
            <div class="panel-body">
                <div class="row">
                    <form role="form" method="post">
                        <div class="col-lg-6">


                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon">Date du course</span>
                                <input type="text" name="race_date" class="form-control" value="<?php echo $data['race_date'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Réunion</span>
                                <select class="form-control" name="meeting">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['meeting'] == '1') ? 'selected="selected"' : ''; ?>>1</option>
                                    <option <?php echo ($data['meeting'] == '2') ? 'selected="selected"' : ''; ?>>2</option>
                                    <option <?php echo ($data['meeting'] == '3') ? 'selected="selected"' : ''; ?>>3</option>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Course</span>
                                <select class="form-control" name="race_number">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['race_number'] == '1') ? 'selected="selected"' : ''; ?>>1</option>
                                    <option <?php echo ($data['race_number'] == '2') ? 'selected="selected"' : ''; ?>>2</option>
                                    <option <?php echo ($data['race_number'] == '3') ? 'selected="selected"' : ''; ?>>3</option>
                                    <option <?php echo ($data['race_number'] == '4') ? 'selected="selected"' : ''; ?>>4</option>
                                    <option <?php echo ($data['race_number'] == '5') ? 'selected="selected"' : ''; ?>>5</option>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Inscription</span>
                                <input type="text" name="price" class="form-control" value="<?php echo $data['price'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Recul.</span>
                                <input type="text" name="recul_gain" class="form-control" value="<?php echo $data['recul_gain'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Recul.</span>
                                <input type="text" name="recul_meter" class="form-control" value="<?php echo $data['recul_meter'] ?>" />
                                <span class="input-group-addon">m</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Max gain</span>
                                <input type="text" name="max_gain" class="form-control" value="<?php echo $data['max_gain'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Age min.</span>
                                <input type="text" name="age_min" class="form-control" value="<?php echo $data['age_min'] ?>" />
                                <span class="input-group-addon">ans</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Age max.</span>
                                <input type="text" name="age_max" class="form-control" value="<?php echo $data['age_max'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Prize</span>
                                <input type="text" name="victory_price" class="form-control" value="<?php echo $data['victory_price'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Statut</span>
                                <select class="form-control" name="status">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['status'] == '1') ? 'selected="selected"' : ''; ?> value="1">Activé</option>
                                    <option <?php echo ($data['status'] == '0') ? 'selected="selected"' : ''; ?> value="0">Désactivé</option>
                                </select>
                            </div>
                            <button class="btn btn-success" type="submit">Sauvegarder</button>
                            <button class="btn btn-danger" type="reset" onclick="history.back()">Annuler</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>
</div>


