<!-- DataTables JavaScript -->
<script src="/themes/admin/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="/themes/admin/bootstrap/datatables/dataTables.bootstrap.min.js"></script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Course :: modifier :: <?php echo $data['name'] ?></h1>

        <!-- /.col-lg-12 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Informations de l'écurie
            </div>
            <div class="panel-body">
                <div class="row">
                    <form role="form" method="post">
                        <input type="hidden" name="id" value="<?php echo $data['id'] ?>">
                        <div class="col-lg-6">

                            <div class="form-group input-group">
                                <span class="input-group-addon">Nom</span>
                                <input type="text" name="name" class="form-control" value="<?php echo $data['name'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Catégorie</span>
                                <select class="form-control" name="category_id">
                                    <option>--choisir--</option>
                                    <?php
                                    foreach(Apps::getModel('Race_Category')->getCategories() as $item){
                                        $selected = ($item['id'] == $data['category_id']) ? 'selected="selected"' : '';
                                    ?>
                                    <option <?php echo $selected ?> value="<?php echo $item['id'] ?>"><?php echo $item['title'] ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Groupe</span>
                                <select class="form-control" name="group_id">
                                    <option>--choisir--</option>
                                    <?php
                                    foreach(Apps::getModel('Race_Group')->getGroups() as $item){
                                        $selected = ($item['id'] == $data['group_id']) ? 'selected="selected"' : '';
                                        ?>
                                        <option <?php echo $selected ?> value="<?php echo $item['id'] ?>"><?php echo $item['group_name'] ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Hippodrome</span>
                                <select class="form-control" name="hippodrome_id">
                                    <option>--choisir--</option>
                                    <?php
                                    foreach(Apps::getModel('Race_Hippodrome')->getHippodromes() as $item){
                                        $selected = ($item['id'] == $data['hippodrome_id']) ? 'selected="selected"' : '';
                                        ?>
                                        <option <?php echo $selected ?> value="<?php echo $item['id'] ?>"><?php echo $item['title'] ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Type</span>
                                <select class="form-control" name="type_id">
                                    <option>--choisir--</option>
                                    <?php
                                    foreach(Apps::getModel('Race_Type')->getTypes() as $item){
                                        $selected = ($item['id'] == $data['type_id']) ? 'selected="selected"' : '';
                                        ?>
                                        <option <?php echo $selected ?> value="<?php echo $item['id'] ?>"><?php echo $item['title'] ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Piste</span>
                                <select class="form-control" name="piste_id">
                                    <option>--choisir--</option>
                                    <?php
                                    foreach(Apps::getModel('Race_Piste')->getPistes() as $item){
                                        $selected = ($item['id'] == $data['piste_id']) ? 'selected="selected"' : '';
                                        ?>
                                        <option <?php echo $selected ?> value="<?php echo $item['id'] ?>"><?php echo $item['title'] ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Longueur</span>
                                <input type="text" name="lenght" class="form-control" value="<?php echo $data['lenght'] ?>" />
                                <span class="input-group-addon">m</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Corde</span>
                                <select class="form-control" name="corde">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['corde'] == 'D') ? 'selected="selected"' : ''; ?> value="D">Droite</option>
                                    <option <?php echo ($data['corde'] == 'G') ? 'selected="selected"' : ''; ?> value="G">Gauche</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon">Date du course</span>
                                <input type="text" name="race_date" class="form-control" value="<?php echo $data['race_date'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Réunion</span>
                                <select class="form-control" name="meeting">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['meeting'] == '1') ? 'selected="selected"' : ''; ?>>1</option>
                                    <option <?php echo ($data['meeting'] == '2') ? 'selected="selected"' : ''; ?>>2</option>
                                    <option <?php echo ($data['meeting'] == '3') ? 'selected="selected"' : ''; ?>>3</option>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Course</span>
                                <select class="form-control" name="race_number">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['race_number'] == '1') ? 'selected="selected"' : ''; ?>>1</option>
                                    <option <?php echo ($data['race_number'] == '2') ? 'selected="selected"' : ''; ?>>2</option>
                                    <option <?php echo ($data['race_number'] == '3') ? 'selected="selected"' : ''; ?>>3</option>
                                    <option <?php echo ($data['race_number'] == '4') ? 'selected="selected"' : ''; ?>>4</option>
                                    <option <?php echo ($data['race_number'] == '5') ? 'selected="selected"' : ''; ?>>5</option>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Inscription</span>
                                <input type="text" name="price" class="form-control" value="<?php echo $data['price'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Recul.</span>
                                <input type="text" name="recul_gain" class="form-control" value="<?php echo $data['recul_gain'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Recul.</span>
                                <input type="text" name="recul_meter" class="form-control" value="<?php echo $data['recul_meter'] ?>" />
                                <span class="input-group-addon">m</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Max gain</span>
                                <input type="text" name="max_gain" class="form-control" value="<?php echo $data['max_gain'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Age min.</span>
                                <input type="text" name="age_min" class="form-control" value="<?php echo $data['age_min'] ?>" />
                                <span class="input-group-addon">ans</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Age max.</span>
                                <input type="text" name="age_max" class="form-control" value="<?php echo $data['age_max'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Prize</span>
                                <input type="text" name="victory_price" class="form-control" value="<?php echo $data['victory_price'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Statut</span>
                                <select class="form-control" name="status">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['status'] == '1') ? 'selected="selected"' : ''; ?> value="1">Activé</option>
                                    <option <?php echo ($data['status'] == '0') ? 'selected="selected"' : ''; ?> value="0">Désactivé</option>
                                </select>
                            </div>
                            <button class="btn btn-success" type="submit">Sauvegarder</button>
                            <button class="btn btn-danger" type="reset" onclick="history.back()">Annuler</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                Les participants à la course
            </div>
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-race-cheval">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Cheval</th>
                            <th>Sexe/Age</th>
                            <th>Entraineur</th>
                            <th>Jockey/Diver</th>
                            <th>Musique</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php  foreach($horses as $item) {  ?>
                            <tr class="">
                                <td><?php echo $item['id'] ?></td>
                                <td><a href="/admin/horse/edit/id/<?php echo $item['id'] ?>"><?php echo $item['name'] ?></a></td>
                                <td><?php echo $item['sexe'] ?>/<?php echo $item['age'] ?></td>
                                <td class="center"><?php echo $item['entraineur'] ?></td>
                                <td class="center"><?php echo $item['jockey'] ?></td>
                                <td class="center"><?php echo Apps::getModel('Horse')->get5LastPerfs($item['sexe'], $item['id']) ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
<script>
    $(document).ready(function() {
        $('#dataTables-race-cheval').DataTable({
            responsive: true
        });
    });
</script>

