<div>
    Niveau :
    <ul>
        <li>
            Niv 0 : Novice<br>
            Avantages :
            <ul>
                <li>Nombre des chevaux max : 10</li>
                <li>Nombre des poulinières + étalons max : 05</li>
                <li>Nombre des points d'entrainement : 120 points</li>
            </ul>
            Passer au prochain niveau :
            <ul>
                <li>Il faut gagner 10 courses (defi entraineur)</li>
                <li>Il faut avoir gagner 100 000 de gains (defi entraineur)</li>
                <li>extension (payer 100 000)</li>
            </ul>
        </li>
        <li>
            Niv 1 : Amateur<br>
            Avantages :
            <ul>
                <li>Nombre des chevaux max : 20</li>
                <li>Nombre des poulinières + étalons max : 10</li>
                <li>Nombre des points d'entrainement : 240 points</li>
            </ul>
            Passer au prochain niveau :
            <ul>
                <li>Il faut gagner 20 courses (defi entraineur)</li>
                <li>Il faut avoir gagner 200 000 de gains (defi entraineur)</li>
                <li>extension (payer 100 000)</li>
            </ul>
        </li>
        <li>
            Niv 2 : Moyenne<br>
            Avantages :
            <ul>
                <li>Nombre des chevaux max : 30</li>
                <li>Nombre des poulinières + étalons max : 15</li>
                <li>Nombre des points d'entrainement : 360 points</li>
            </ul>
            Passer au prochain niveau :
            <ul>
                <li>Il faut gagner 30 courses (defi entraineur)</li>
                <li>Il faut avoir gagner 300 000 de gains (defi entraineur)</li>
                <li>extension (payer 100 000)</li>
            </ul>
        </li>
        <li>
            Niv 3 : Grande<br>
            Avantages :
            <ul>
                <li>Nombre des chevaux max : 40</li>
                <li>Nombre des poulinières + étalons max : 20</li>
                <li>Nombre des points d'entrainement : 480 points</li>
                <li>extension (payer 100 000) pour débloquer les limités des nombres de chevaux (05 suppl.)</li>
            </ul>
        </li>
    </ul>

    Affichage :
    <ul>
        <li>Recapitulatif : niveau, chevaux max, </li>
        <li>statistique : course fait, gagné, placé, classement </li>
        <li>liste chevaux course prévu</li>
        <li>liste chevaux en vente</li>
        <li>liste des chevaux de course</li>
        <li>liste des chevaux de production</li>
    </ul>
</div>