Type de course :
<ul>
    <li>qualification</li>
    <li>à reclamer</li>
    <li>à conditions</li>
</ul>

Qualifications :
<ul>
    <li>2 ans : 1'21.5 attele, 1'22.0 monté</li>
    <li>3 ans : 1'20.0 attele, 1'20.5 monté</li>
    <li>4 ans : 1'18.0 attele, 1'18.5 monté</li>
    <li>5 ans et + : 1'17.5 attele, 1'18.0 monté</li>
</ul>
Groupe I : https://fr.wikipedia.org/wiki/Sport_hippique#Groupe_I
<br>
Groupe II : https://fr.wikipedia.org/wiki/Sport_hippique#Groupe_II
<br>
Groupe III : https://fr.wikipedia.org/wiki/Sport_hippique#Groupe_III
<br>
Affichage :
<ul>
    <li>Liste des courses du jour, hier et demaine. + fonction de rechreche des dates anterieur  + resultat</li>
    <li>Les paris sont ouverts du jour du course</li>
</ul>