<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Administration</title>

	<!-- Bootstrap Core CSS -->
	<link href="/themes/admin/css/bootstrap.min.css" rel="stylesheet">

	<link href="/themes/admin/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet">

	<!-- MetisMenu CSS -->
	<link href="/themes/admin/css/metisMenu.min.css" rel="stylesheet">

	<!-- Timeline CSS -->
	<link href="/themes/admin/css/timeline.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="/themes/admin/css/sb-admin-2.css" rel="stylesheet">

	<!-- Morris Charts CSS -->
	<link href="/themes/admin/css/morris.css" rel="stylesheet">

	<!-- Custom Fonts -->
	<link href="/themes/admin/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<!-- script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script  -->
	<!--script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script -->
	<![endif]-->
	<!-- jQuery -->
	<script src="/themes/admin/js/jquery.min.js"></script>
	<script src="/themes/admin/jquery-ui-1.11.4/jquery-ui.min.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="/themes/admin/js/bootstrap.min.js"></script>

	<!-- Metis Menu Plugin JavaScript -->
	<script src="/themes/admin/js/metisMenu.min.js"></script>






	<!-- Custom Theme JavaScript -->
	<script src="/themes/admin/js/sb-admin-2.js"></script>

</head>
<body class="">
	<div id="wrapper">
		<!-- Navigation -->
		<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
			<div class="navbar-header">
				<?php Layout::render('admin/menu-top'); ?>
			</div>
			<!-- /.navbar-header -->
			<?php Layout::render('admin/menu-header'); ?>
			<?php Layout::render('admin/menu-left'); ?>
		</nav>
		<div id="page-wrapper">
			<?php Layout::render('admin/message'); ?>
			<?php echo Layout::renderView($content) ?>
		</div>
		<!-- /#page-wrapper -->
	</div>
	<!-- /#wrapper -->



</body>
</html>