<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo Layout::getTitle() ?></title>

    <!-- Bootstrap Core CSS -->
    <link href="/themes/front/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/themes/front/css/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/themes/front/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/themes/front/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/themes/front/css/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/themes/front/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <!-- script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script  -->
    <!--script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script -->
    <![endif]-->

</head>
<body class="">
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <?php Layout::render('front/menu-top'); ?>
        </div>
        <!-- /.navbar-header -->
        <?php Layout::render('front/menu-header'); ?>
        <?php Layout::render('front/menu-left'); ?>
    </nav>
    <div id="page-wrapper">
        <?php echo Layout::renderView($content) ?>
    </div>
    <!-- /#page-wrapper -->
</div>
<!-- /#wrapper -->


<!-- jQuery -->
<script src="/themes/front/js/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/themes/front/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="/themes/front/js/metisMenu.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="/themes/front/js/sb-admin-2.js"></script>
</body>
</html>