<ul class="sous-menu-help">
	<li><a href="/help/stable/">Ecurie</a></li>
	<li><a href="/help/stable/">Entraineur</a></li>
	<li><a href="/help/jockey/">Jockey/Driver</a></li>
	<li><a href="/help/breedings/">Elevages</a></li>
	<li><a href="/help/shop/">Enchères</a></li>
	<li><a href="/help/races/">Courses</a></li>
</ul>
<div style="clear: both">
<div>
	Niveau : même niveau que l'écurie
</div>
<div>
	Vos Etalons<br>
	<ul>
		<li>
			Qualification :
			<ul>
				<li>être un male</li>
				<li>âge entre 5 à 25 ans</li>
				<li>Soit avoir été classés dans les trois premiers d’une course de Groupe I. (100 saillies annuelles)</li>
				<li>Soit avoir obtenu au cours de leur carrière, lors de courses victorieuses enregistrées dans des épreuves organisées sur des hippodromes homologués, 6 fois une réduction kilométrique inférieure ou égale à :
					<ul>
						<li>1’16”5 à l’âge de 3 ans,</li>
						<li>1’15”5 à l’âge de 4 ans,</li>
						<li>1’14”5 à l’âge de 5 ans,</li>
						<li>1’13”5 à l’âge de 6 ans ou plus</li>
					</ul>
					Une  victoire  dans  une  course  de Groupe  II  équivaut  à  deux  victoires  avec  le  record  requis,  tandis qu’un classement de 2ème
					ou de 3ème dans cette catégorie de courses équivaut à une victoire avec le record requis.
					(100 saillies annuelles)
				</li>
				<li>être fils d’une jument ou frère utérin d’un cheval ayant gagné une course de Groupe I ou II, (60 saillies annuelles)</li>
				<li>Soit avoir obtenu un total de gains d’un minimum de 100.000 € à quatre ans, ou 200.000 € à cinq ans ou 280.000 € à six ans ou plus, (60 saillies annuelles)</li>
			</ul>
		</li>
		<li>
			Niveau de réproduction de 1 à 5 selon l'ITR.
			<ul>
				<li>
					Classement de l'ITR :
					<ul>
						<li>ITR entre 170 et + évaluation élevage ------à 125 000 oros(approuvé)</li>
						<li>ITR entre 160 et 169 évaluation élevage ------à 75 000 oros(autorisé)</li>
						<li>ITR entre 150 et 159 évaluation élevage ------à 50 000 oros(autorisé)</li>
						<li>ITR entre 140 et 149 évaluation élevage ------à 25 000 oros(accepté)</li>
						<li>ITR entre 120 et 139 évaluation élevage ------à 12 500 oros(accepté)</li>
					</ul>
				</li>
				<li>
					Comment avoir l'ITR :<br>
					<ul>
						<li>combine le gain annuel et le classement des chevaux (chacun vaut 50% de l’indice)</li>
					</ul>
				</li>
			</ul>
		</li>
		<li>
			Héritage génétique
			<ul>
				<li>
					A la naissance du poulain, son BTR est déterminé en faisant la moyenne des BTR de ses parents,
				</li>
				<li>
					puis l'indice évolue au cours de sa vie, en fonction de ses performances.
				</li>
			</ul>
		</li>
	</ul>

	Vos poulinières<br>
	<ul>
		<li>
			Qualification :
			<ul>
				<li>âge entre 5 à 12 ans</li>
				<li>être qualifiée</li>
				<li>avoir obtenu une victoire au moins dans une course</li>
			</ul>
		</li>
		<li>
			Niveau de réproduction de 1 à 5 selon le niveau réproducteur du père.<br>
			Mais on peut l'augmenter en fonction de votre ITR si supérieur à l'ITR du père<br>
			http://tpetrotteursfrancais.weebly.com/leacutelevage.html
		</li>
	</ul>

	Vos Poulains<br>
	<ul>
		<li>Vente entre Septembre et Novembre seulement (pour les 18 mois)</li>
	</ul>
</div>
<div>
	Affichage :
	<ul>
		<li>Liste de stock des saillies</li>
		<li>Liste de vos étalons</li>
		<li>Liste de vos poulinières</li>
		<li>Liste de vos poulains</li>
		<li>Liste de vos chevals entant qu'eleveur</li>
	</ul>
</div>
	</div>