<ul class="sous-menu-help">
	<li><a href="/help/stable/">Ecurie</a></li>
	<li><a href="/help/stable/">Entraineur</a></li>
	<li><a href="/help/jockey/">Jockey/Driver</a></li>
	<li><a href="/help/breedings/">Elevages</a></li>
	<li><a href="/help/shop/">Enchères</a></li>
	<li><a href="/help/races/">Courses</a></li>
</ul>
<div style="clear: both">
Il faut un license de course délivré par TurfoLand pour être jockey ou driver<br>
License :  course special tous les 15 jours (1er jour de course), atteindre un temps ou rang spécifique <br>

Niveau : le niveau a une impact sur le course, plus il est élévé plus il a un bon fiinish
<ul>
	<li>
		Niv 0 : Sans license<br>
		Il faut un license pour passer au prochain niveau
	</li>
	<li>
		Niv 1 : Amateur<br>
		Il faut avoir un gain de 500 000 ou gagner un trophé pour passer au prochain niveau
	</li>
	<li>
		Niv 2 : National<br>
		Il faut avoir un gain de 1 000 000 ou gagner un trophé pour passer au prochain niveau
	</li>
	<li>
		Niv 3 : International
	</li>
</ul>
Prix pour les meilleurs
<ul>
	<li>Sulky d'or pour les drivers</li>
	<li>Étrier d'or pour les jockeys de trot monté</li>
	<li>Cravache d'or pour les jockeys de plat et d'obstacle</li>
</ul>
<div>
	Affichage :
	<ul>
		<li>Statistique : stat resultat(carrière+année encours), niveau, nom+prenom, prix, ...</li>
		<li>Configuration : prix, choix jour d'engagement, ...</li>
		<li>Demande de jockey/driver</li>
		<li>Courses à venir</li>
		<li>Courses courues</li>
		<li>Menu droite : 03 classement du prix et votre rang</li>
	</ul>
</div>
	<div>
		Artifices
		<ul>
			<li>
				Le déferrage : (special trot) augmenter vitesse et resistance<br>
				un trotteur déferré pour la première fois peut réellement courir au-dessus de sa valeur et créer la surprise<br>
				- Cheval déferré des antérieurs : DA<br>
				- Cheval déferré des postérieurs : DP<br>
				- Cheval déferré des quatre pieds : D4<br>
			</li>
			<li>
				Les œillères : diminue la panique<br>
				- Cheval qui porte des œillères : Une croix cerclée<br>
				- Cheval qui porte des œillères australiennes : Un A cerclé<br>
			</li>
		</ul>
	</div>

	</div>