<ul class="sous-menu-help">
    <li><a href="/help/stable/">Ecurie</a></li>
    <li><a href="/help/trainer/">Entraineur</a></li>
    <li><a href="/help/jockey/">Jockey/Driver</a></li>
    <li><a href="/help/breedings/">Elevages</a></li>
    <li><a href="/help/shop/">Enchères</a></li>
    <li><a href="/help/races/">Courses</a></li>
</ul>
<div style="clear: both">
Conditions pour être acheteable :
<ul>
    <li>pas course prévue</li>
    <li>fatigue = 0%</li>
    <li>en possession de son proprietaire pendant 120 jours pour les 2 ans et 90 jours pour les 3ans et +</li>
</ul>
Affichage :
<ul>
    <li>Liste des achats en cous</li>
    <li>Liste des enchères achat direct avec prix minimum, le premier max gagne</li>
    <li>Liste des enchères des saillie, achat direct</li>
    <li>Liste des enchères de saillie, par tirage</li>
</ul>
    </div>