<ul class="sous-menu-help">
    <li><a href="/help/stable/">Ecurie</a></li>
    <li><a href="/help/trainer/">Entraineur</a></li>
    <li><a href="/help/jockey/">Jockey/Driver</a></li>
    <li><a href="/help/breedings/">Elevages</a></li>
    <li><a href="/help/shop/">Enchères</a></li>
    <li><a href="/help/races/">Courses</a></li>
</ul>

<div style="clear: both">

<ul>
    <li>16h d'entrainement max /cheval</li>
    <li>4h max pour chaque critère</li>
    <li>1h d'entrainement au dessus de 2h génère du fatigue (10%)</li>
    <li>1h d'entrainement au dessous de 2h génère du fatigue (-10%)</li>
    <li>apres course fatigue  et physique à 80%, et entrainement à 2</li>
    <li>-5% fatigue/jour de répos</li>
    <li>si fatigue > 100%, cheval->(blessé)inactif pendant 3 semaines</li>
    <li>si fatigue > 150%, cheval->(meurt)inactif</li>
</ul>
