<!-- START MAIN NAVIGATION -->
<div class="menu">
    <ul id="nav" class="sf-menu">
        <li class="nav-icon-home current_page_item">
            <a href="index.html">
                Ecurie
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>

        </li>
        <li class="nav-icon-idea">
            <a href="#">
                Entraineur
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>

        </li>
        <li class="nav-icon-team">
            <a href="#">
                Jockey/Diver
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>

        </li>
        <li class="nav-icon-lab">
            <a href="#">
                Elevages
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>

        </li>
        <li class="nav-icon-works">
            <a href="#">
                Courses
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>

        </li>
        <li class="nav-icon-cart">
            <a href="#">
                March&eacute;
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>

        </li>
        <li class="nav-icon-radio">
            <a href="#">
                En direct
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>

        </li>
        <li class="nav-icon-first">
            <a href="#">
                Classements
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>

        </li>
    </ul>
</div>
<!-- END MAIN NAVIGATION -->