<!-- START MAIN NAVIGATION -->
<?php
$menus = array(
    array( 'link' => '/stable/', 'title' => Text::__('Stable'), 'class' => 'fa-home' ),
    array( 'link' => '/trainer/', 'title' => Text::__('Trainer'), 'class' => 'fa-eye' ),
    array( 'link' => '/jockey/', 'title' => Text::__('Jockey'), 'class' => 'fa-group' ),
    array( 'link' => '/breedings/', 'title' => Text::__('Breedings'), 'class' => 'fa-venus-mars' ),
    array( 'link' => '/races/', 'title' => Text::__('Races'), 'class' => 'fa-flag-checkered' ),
    array( 'link' => '/shop/', 'title' => Text::__('Shop'), 'class' => 'fa-legal' ),
    array( 'link' => '/live/', 'title' => Text::__('Live'), 'class' => 'fa-video-camera' ),
    array( 'link' => '/rankings/', 'title' => Text::__('Rankings'), 'class' => 'fa-trophy' ),
    array( 'link' => '/finance/', 'title' => Text::__('Finances'), 'class' => 'fa-bank' ),
);
$currentController = '/' . lcfirst(Request::getInstance()->getController()) . '/';
if($currentController == '/index/'){
    $currentController =  '/stable/';
}
?>

<div class="menu  col-md-12">
    <ul id="nav" class="sf-menu">
        <?php foreach( $menus as $menu) { ?>
        <li class=" <?php echo ($menu['link']==$currentController) ? 'current_page_item' : ''?> ">
            <i class="fa <?php echo $menu['class'] ?>"></i>
            <a href="<?php echo $menu['link'] ?>">
                <?php echo $menu['title'] ?>
                <div style="position:absolute; left: 50%;">
                    <span class="triangle">&nbsp;</span>
                </div>
            </a>
        </li>
        <?php } ?>
    </ul>
</div>
<!-- END MAIN NAVIGATION -->