<div class="container">
    <div class="row">
        <div id="last-tweets-3" class="widget-first span6 widget last-tweets">
            <ul>
                <li>
                    <i class="fa fa-user fa-lg"></i><span>Ecurie D'Orion</span>
                    <i class="fa fa-star fa-lg star-level-yes"></i>
                    <i class="fa fa-star-o fa-lg star-level-no"></i>
                    <i class="fa fa-star-o fa-lg star-level-no"></i>
                    <i class="fa fa-power-off fa-lg"></i>
                </li>
                <li><i class="fa fa-bank fa-lg"></i><span> 4 300 000 turfoos</span></li>
            </ul>
        </div>
        <div id="social-icon" class="widget-2 widget-last span2 widget widget_text">
            <div class="textwidget">
                <a href="/help/" class="fa help" >Besoin d'aide ?</a>
                <a href="#" class="socials-small facebook-small" title="Facebook"  >facebook</a>
                <a href="#" class="socials-small twitter-small" title="Twitter"  >twitter</a>
                <a href="#" class="socials-small google-small" title="Google"  >google</a>
            </div>
        </div>
    </div>
</div>