Le Stud-Book du TurfoLand comprend :<br>
<ul>
    <li>un répertoire des étalons approuvés pour produire dans la race,</li>
    <li>un répertoire des juments pouvant produire dans la race,</li>
    <li>un répertoire des poulains inscrits au titre de l’ascendance,</li>
</ul>
Poulains
<ul>
    <li>
        Issu d’une saillie
        <ul>
            <li>L’étalon père du produit doit être approuvé pour la production</li>
            <li>La jument mère du produit doit être inscrite au Stud-Book</li>
        </ul>
    </li>
    <li>Ayant reçu un nom attribué avant le 30 septembre de l'année de naissance</li>
    <li>Qualifié, 1' 24.0 au 2ans sur 2400m</li>
</ul>
Etalons
<ul>
    <li></li>
</ul>
Poulinières
<ul>
    <li>être qualifiée</li>
    <li>avoir obtenu une victoire au moins dans une course</li>
</ul>

Liste des catégorie : http://pro.letrot.com/siteletrotws/publication?type=STUDBOOK

