<?php
$sessionUser = Session::getUser();
$stable = Apps::getModel('Stable')->load($sessionUser['id'])->getData();

$oHorse = Apps::getModel('Horse')->load($horseId);
$horse = $oHorse->getData();
//print_r($horse);die;
?>
<input type="hidden" id="horse_id" value="<?php echo $horse['id'] ?>" />
<div class="col-md-12">
	<div class="panel panel-info">
		<!--a href="javascript:history.back()" class="pull-left"><b><i class="fa fa-arrow-circle-left "></i> Retour</b></a-->
		<a href="javascript:void(0)" onclick="window.opener.location.reload();window.close()" class="pull-right"><b><i class="fa fa-refresh  "></i> Fermer et actualiser</b></a>
	</div>
	<div style="clear:both"></div>
</div>

<div class="col-md-12 course-content horse-detailed" style="margin-top: 20px">
	<div class="panel panel-info">
		<div class="panel-heading" style="padding: 5px 10px;">
			<h4 style="float:left;margin:0;font-size: 19px;"><?php echo $horse['name'] ?></h4>
			<span class="col-xs-7" style="font-size: 15px;color:#5f5e5e;">- <?php echo $horse['type_name'] ?> de <?php echo $horse['age'] ?> ans -</span>
			<div style="clear:both"></div>
		</div>
		<div class="panel-body">
			<ul class="col-xs-6" style="list-style: none;">
				<li>
					<span class="col-xs-7"><b>Specialité :</b></span><span class="col-xs-5"><?php echo $oHorse->getSpecialite() ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Indice :</b></span><span class="col-xs-5"><?php echo $oHorse->getIndice() ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Réproduction :</b></span><span class="col-xs-5"><?php echo $oHorse->getIndiceReproduction() ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Robe :</b></span><span class="col-xs-5"><?php echo (is_null($horse['robe'])) ? '-' : ucfirst($horse['robe']); ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Corde :</b></span><span class="col-xs-5"><?php echo ($horse['corde']=='G') ? 'Gauche' : 'Droite'; ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Valeur :</b></span><span class="col-xs-5"><?php echo number_format($horse['price'], 0, '.', ' ') ?> <?php echo Text::__('turfoos') ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Résultats :</b></span><span class="col-xs-5"><?php echo $oHorse->getResultats() ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Gains :</b></span><span class="col-xs-5"><?php echo number_format($horse['gains'], 0, '.', ' ') ?> <?php echo Text::__('turfoos') ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Musique :</b></span><span class="col-xs-5"><?php echo $oHorse->get5LastPerfs($horse['sexe']) ?></span>
				</li>
			</ul>

			<ul class="col-xs-6" style="list-style: none;">
				<li>
					<span class="col-xs-7"><b>Père :</b></span>
					<span class="col-xs-5">
						<?php echo $oHorse->getName($horse['father'], $horse['father_id'], $horse['father_status']) ?>
					</span>
				</li>
				<li>
					<span class="col-xs-7"><b>Mère :</b></span>
					<span class="col-xs-5">
						<?php echo $oHorse->getName($horse['mother'], $horse['mother_id'], $horse['mother_status']) ?>
					</span>
				</li>
				<li>
					<?php //$fatherOfMotherData = $oHorse->getFatherOfMother() ?>
					<span class="col-xs-7"><b>Père de mère :</b></span>
					<span class="col-xs-5">
						<?php echo $oHorse->getName($horse['father_mother'], $horse['father_mother_id'], $horse['father_mother_status']) ?>
					</span>
				</li>
				<li>
					<span class="col-xs-7"><b>Propriètaire :</b></span><span class="col-xs-5"><?php echo Apps::getModel('Stable')->getName($horse['proprio'], $horse['proprio_id']) ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Entraineur :</b></span><span class="col-xs-5"><?php echo Apps::getModel('Stable')->getName($horse['trainer'], $horse['trainer_id']) ?></a></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Eleveur :</b></span><span class="col-xs-5"><?php echo Apps::getModel('Stable')->getName($horse['eleveur'], $horse['eleveur_id']) ?></span>
				</li>
			</ul>
		</div>
	</div>
</div>

<div class="col-md-12 course-content horse-detailed" style="margin-top: 20px">
	<div class="panel panel-info">
		<div style="padding: 5px 10px;" class="panel-heading">
			<span class="col-md-12 fiche-cheval-sous-titre">Prochaine course</span>
		</div>
		<div class="panel-body"style="padding-left:11px;">

			<div class="valid-race-list col-xs-12" style="margin-top: 20px;">
				<?php
				$isEngagedInRace = $oHorse->isEngagedInRace();
				if( $isEngagedInRace ) {
					if(isset($isEngagedInRace['race_id'])) {
						$race = Apps::getModel('Race')->load($isEngagedInRace['race_id'])->getData();
						$isTemp = false;
					}else{
						$race = Apps::getModel('Race_Tmp')->load($isEngagedInRace['race_tmp_id'])->getData();
						$isTemp = true;
					}
				?>
				<div class="col-xs-12 well well-sm" style="padding: 0;">
					<h4 class="col-xs-7" style="font-size: 12px"><?php echo date('d M Y', strtotime($race['race_date'])) ?> -
						<?php if(!$isTemp) { ?>
							<?php echo date('H\Hi', strtotime($race['race_date'])) ?>	-
						<?php } ?>
						<b><a href=""><?php echo Apps::getModel('Race')->getName($race['name'], $race['id'], $isTemp) ?></b> -
						<b><?php echo Apps::getModel('Race_Hippodrome')->getName($race['hippodrome_id']) ?></b> - <i style="font-family: Arial; text-transform: none"><?php echo $race['category_name'] ?></i>
						<br>
						<i style="font-family: Arial; text-transform: none">
							<?php echo $race['group_name'] ?> - <?php echo number_format($race['lenght'], 0, '.', ' ') ?>m -
							<?php echo ($race['code'] == 'a') ? 'Attelé' : (($race['code']=='m') ? 'Monté' : 'Plat') ; ?> -
							Corde à <?php echo Apps::getModel('Race')->getCorde($race); ?> -
							Piste en <?php echo $race['piste_name'] ?> <br />
							Pour les chevaux de <b><?php echo Apps::getModel('Race')->getAgeMinMax($race); ?></b>
							<?php echo Apps::getModel('Race')->getGainsMax($race); ?><br>

						</i>
					</h4>
					<span class="col-xs-5">
						<?php if($oHorse->getData('is_qualified')) { ?>
						<ul class="col-xs-12" style="list-style: none;margin-top: 10px;">
							<li class="col-xs-12">
								<span class="col-xs-4"><b>Gains :</b></span>
								<span class="col-xs-8 a-right"><?php echo Apps::getModel('Race')->getRacePrizeAjax($race) . ' '  .Text::__('turfoos'); ?></span>
							</li>
							<li class="col-xs-12">
								<span class="col-xs-4"><b>Engagement :</b></span>
								<span class="col-xs-8 a-right"><?php echo number_format($race['price'], 0, '.', ' ') . ' '  .Text::__('turfoos') ?></span>
							</li>
						</ul>
						<?php } ?>
						<?php
						if($oHorse->isOwner($stable['id'])){
							if($isTemp && $isEngagedInRace['status'] == 1) {
						?>
								<span class="col-xs-5 pull-right" style="margin: 10px 11px 10px;">
									<button type="button" class=" pull-right disengaged-this-race btn btn-success btn-xs btn-social" rel="<?php echo $race['id'] ?>|<?php echo $race['price'] ?>"><i class="fa fa-times "></i> <b>Se désinscrire</b></button>
								</span>
						<?php
							}
						}
						?>
					</span>
				</div>
				<?php }else{ ?>

				<ul class="col-xs-12" style="list-style: none;">
					<li><?php echo strtoupper($horse['name']) ?> n'est pas inscrit(e) dans une course</li>
					<?php if($oHorse->isOwner($stable['id']) && $horse['status'] == 1 ){ ?>
					<li><button type="button" class="get-valid-race btn btn-success btn-xs btn-social"><i class="fa fa-pencil-square-o"></i> <b>S'engager dans une course</b></button></li>
					<?php } ?>
				</ul>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
<div class="col-md-12 horse-detailed">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs">
		<li class="active fiche-cheval-sous-titre"><a data-toggle="tab" href="#courses">Courses</a></li>
		<?php if($oHorse->isOwner($stable['id'])){ ?>
		<li class="fiche-cheval-sous-titre"><a data-toggle="tab" href="#caracteres">Caractéristiques et Entrainements</a></li>
		<?php } ?>
		<li class="fiche-cheval-sous-titre"><a data-toggle="tab" href="#reproductions">Réproductions</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div id="courses" class="tab-pane fade in active horse-race-list" style="padding: 12px;">
			<table class="table">
				<thead>
				<tr>
					<td class="a-left"><b>Date</b></td>
					<td>&nbsp;</td>
					<td><b>Hippodrome</b></td>
					<td><b>Prix</b></td>
					<td><b>Corde</b></td>
					<td><b>Distance</b></td>
					<td><b>Place</b></td>
					<td><b>Gains</b></td>
				</tr>
				</thead>
				<tbody>
					<?php
					$horseRaceDone = $oHorse->getRacesDone();
					if(count($horseRaceDone) > 0){
						foreach( $horseRaceDone as $raceDone) {
						?>
						<tr>
							<td class="a-left"><?php echo date('d-m-Y', strtotime($raceDone['race_date'])) ?></td>
							<td><i class="fa ico-course-<?php echo $raceDone['code'] ?>"></i></td>
							<td><?php echo $raceDone['hippo'] ?></td>
							<td><?php echo Apps::getModel('Race')->getName($raceDone['name'], $raceDone['race_id']) ?></td>
							<td><?php echo $raceDone['corde'] ?></td>
							<td><?php echo number_format($raceDone['lenght'], 0, '.', ' ') ?> m</td>
							<td>
								<?php
								if(in_array($raceDone['category_id'], array(3,4))) {
									echo 'Q' . $raceDone['code'];
								}else{
									echo $raceDone['place'] . $raceDone['code'];
								}
								?>
							</td>
							<td><?php echo ($raceDone['gain']>0)?$raceDone['gain']:'-'; ?></td>
						</tr>
						<?php
						}
					}else{ ?>
						<tr>
							<td colspan="8"><?php echo strtoupper($horse['name']) ?> n'a jamais courue</td>
						</tr>
					<?php
					}
					?>
				</tbody>
			</table>
		</div>
		<?php if($oHorse->isOwner($stable['id'])){ ?>
		<div id="caracteres" class="tab-pane fade horse-race-list" style="padding: 12px;">
			<script>
				var actual_fatigue, ecart_fatigue, add_fatigue, new_fatigue;
				var total_perf, previous_perf;
			</script>
			<div class="col-xs-2">&nbsp;</div><div class="col-xs-4">&nbsp;</div><div class="col-xs-1">&nbsp;</div><div class="col-xs-4 a-center"><b>Entrainement (15 heures réstants)</b></div><div class="col-xs-1">&nbsp;</div>
			<?php $perfKey = array(
					'trot' => array('_current', 600, '#0563ac', ''),
					'galop' => array('_current', 600, '#0563ac', ''),
					'endurance' => array('_current', 600, '#0563ac', ''),
					'vitesse' => array('_current', 600, '#0563ac', ''),
					'physique' => array('', 100, '#5aa445', '/<sub>100</sub>'),
					'fatigue' => array('', 100, '#FF7FB6', '%')
				);
			?>
			<?php
			foreach($perfKey as $perf => $value){
				$disabled = 'false';
				if( ($horse['trot_base']== 0 && $perf == 'trot') ||($horse['galop_base']== 0 && $perf == 'galop') ){
					continue;
				}
				if($perf == 'physique'){
					if($horse[$perf . $value[0]] == 100){
						$disabled = 'true';
						$horse['training_' . $perf] = 0;
						$physiqueMarge = 0;
					}else{
						$physiqueMarge = $horse['physique'] + (10 * $horse['training_' . $perf]);
					}
				}

				$totalPerf = $horse['training_trot'] + $horse['training_galop'] + $horse['training_endurance'] + $horse['training_vitesse']+ $horse['training_physique'];
				if( ($totalPerf)> 8){
					$horse['fatigue'] = ($totalPerf - 8) * 10;
				}

				if($horse['training_fatigue'] > 0){
					$horse['fatigue'] = $horse['training_fatigue'];
				}
			?>
			<div class="row" style="margin-top: 10px">
				<span class="col-xs-2 ktr-title"><?php echo ucfirst($perf) ?></span>
				<div id="progressbar-<?php echo $perf ?>" class="col-xs-3 progressbar"></div>
				<span class="col-xs-2 perf-value current-<?php echo $perf ?>">
					<b><?php echo $horse[$perf . $value[0] ] ?><?php echo $value[3]?></b>
					<?php if($perf== 'physique'){ ?>
					<span class="phys-percent"><?php echo $physiqueMarge ?></span><span>/<sub>100</sub></span>
						<input type="hidden" id="phys-percent-value" value="<?php echo $physiqueMarge ?>" />
					<?php } ?>
					<input type="hidden" id="current-<?php echo $perf ?>-value" value="<?php echo $horse[$perf . $value[0]] ?>"/>
				</span>
				<?php if($perf!= 'fatigue'){ ?>
				<div id="slider-<?php echo $perf ?>" class="col-xs-4 sliderbar"></div>
				<input type="text" disabled id="training-<?php echo $perf ?>" value="" size="1" class=" training-value" />
				<?php } ?>
				<script type="text/javascript">
					var progressbar_<?php echo $perf ?> = $( "#progressbar-<?php echo $perf ?>" ).progressbar({value: <?php echo $horse[$perf . $value[0]] ?>, max: <?php echo $value[1] ?> }).find( ".ui-progressbar-value").css({"background": '<?php echo $value[2] ?>'});
					<?php if($perf!= 'fatigue'){ ?>
					var slider_<?php echo $perf ?> = $( "#slider-<?php echo $perf ?>" ).slider({disabled: <?php echo $disabled ?>, animate:true, range: "min", min: 0,max: 4, value:<?php echo $horse['training_' . $perf] ?>,
						slide: function( event, ui ) {
							$( "#training-<?php echo $perf ?>" ).val( ui.value );
						},change: function( event, ui ) {

							actual_fatigue = parseInt($('#current-fatigue-value').val());
							ecart_slider =  total_perf - previous_perf;
							add_fatigue = ecart_slider * 10;
							new_fatigue = actual_fatigue + add_fatigue;

							if( total_perf <= 8)							{
								new_fatigue = 0;
							}
							$("#progressbar-fatigue").progressbar({value: new_fatigue});
							$('#current-fatigue-value').val(new_fatigue);

							//juste affichage
							if (new_fatigue < 0) {
								new_fatigue = 0;
							}
							$('.current-fatigue b').html(new_fatigue + '%');

							<?php if($perf== 'physique'){ ?>
							var phys_percent = parseInt($('#phys-percent-value').val()) + (10*ecart_slider);
							if(phys_percent > 100){
								var phys_percent_affichage = 100;
							}else if(phys_percent < parseInt($('#current-physique').val())){
								var phys_percent_affichage = $('#current-physique').val();
							}else{
								var phys_percent_affichage = phys_percent;
							}
							$('#phys-percent-value').val(phys_percent);
							$('span.phys-percent').html(phys_percent_affichage);
							<?php } ?>
						},start: function( event, ui ) {
							previous_perf = parseInt($( "#slider-physique" ).slider( "value" )) + parseInt($( "#slider-vitesse" ).slider( "value" )) +  parseInt($( "#slider-endurance" ).slider( "value" )) ;
							<?php if($horse['galop_base']== 0){ ?>
							previous_perf+= parseInt($( "#slider-trot" ).slider( "value" ));
							<?php }else{ ?>
							previous_perf+= parseInt($( "#slider-galop" ).slider( "value" ));
							<?php } ?>
							console.log(previous_perf);
						},stop: function( event, ui ) {
							total_perf = parseInt($( "#slider-physique" ).slider( "value" )) + parseInt($( "#slider-vitesse" ).slider( "value" )) +  parseInt($( "#slider-endurance" ).slider( "value" )) ;
							<?php if($horse['galop_base']== 0){ ?>
							total_perf+= parseInt($( "#slider-trot" ).slider( "value" ));
							<?php }else{ ?>
							total_perf+= parseInt($( "#slider-galop" ).slider( "value" ));
							<?php } ?>
							console.log(total_perf);
						}
					});
					$( "#training-<?php echo $perf ?>" ).val( $( "#slider-<?php echo $perf ?>" ).slider( "value" ) );
					<?php } ?>
				</script>
			</div>
			<?php
			}
			?>
			<div class="col-xs-7"></div><div class="col-xs-5 a-center"><button class=" btn-social valid-training btn btn-success btn-xs" type="button"><i class="fa fa-sliders"></i><b>Valider les entrainements</b></button></div>
			<div class="clear" style="margin-top: 40px;"></div>
		</div>
		<?php } ?>
		<div id="reproductions" class="tab-pane fade horse-race-list" style="padding: 12px;">
			<ul class="col-xs-6" style="list-style: none;">
				<li>
					<span class="col-xs-7"><b>ITR :</b></span><span class="col-xs-5"><?php echo $horse['itr'] ?></span>
				</li>
			</ul>
			<ul class="col-xs-6" style="list-style: none;">
				<li>
					<span class="col-xs-7"><b>BTR :</b></span><span class="col-xs-5"><?php echo $horse['btr'] ?></span>
				</li>
			</ul>
			<div class="col-xs-12">
				<b class="col-xs-12">Ces progénitures :</b>
				<table class="table">
					<thead>
					<tr>
						<td class="a-left"><b>Cheval</b></td>
						<td><b>Age/Sexe</b></td>
						<td><b>Mère</b></td>
						<td><b>Père de mère</b></td>
						<td><b>Indice</b></td>
					</tr>
					</thead>
					<tbody>
					<?php
					$horseProgenitures = $oHorse->getProgenitures();
					if(count($horseProgenitures) > 0){
						foreach( $horseProgenitures as $enfant) {
							?>
							<tr>
								<td class="a-left">
									<?php echo $oHorse->getName($enfant['name'], $enfant['id'], $enfant['status']) ?>
								</td>
								<td><?php echo $enfant['sexe'] ?>/<?php echo $enfant['age'] ?></td>
								<td>
									<?php echo $oHorse->getName($enfant['mother'], $enfant['mother_id'], $enfant['mother_status']) ?>
								</td>
								<td>
									<?php echo $oHorse->getName($enfant['father_mother'], $enfant['father_mother_id'], $enfant['father_mother_status']) ?>
								</td>
								<td><?php echo $oHorse->getIndice($enfant['quality']) ?></td>
							</tr>
							<?php
						}
					}else{ ?>
						<tr>
							<td colspan="8"><?php echo strtoupper($horse['name']) ?> n'a jamais réproduit</td>
						</tr>
						<?php
					}
					?>
					</tbody>
				</table>
			</div>

			<div class="clear" style="margin-top: 40px;"></div>
		</div>
	</div>
</div>
<div id="alert-engaged-success" title="Inscription à une course">
	Vous êtes inscrit à cette course et le droit d'engagement correspondant a été deduit de votre compte. <br>
	Merci de passer à la préparation de votre prochaine course.
</div>
<div id="alert-disengaged-success" title="Désinscription à une course">
	Vous êtes désinscrit de cette course et le droit d'engagement correspondant deduit a été réstitué vers votre compte.
</div>
<div id="alert-valid-training" title="Vos entrainements">
	Vos entrainements sont enregistrés ! <br>Ils se dérouleront jeudi soir, entre 23h30 et 23h59.
</div>
<script>
	jQuery( document ).ready( function( $ ) {

		$('#alert-valid-training').dialog({
			autoOpen: false,
			width: 400,
			modal: true,
			buttons: [
				{
					text: "Ok",
					click: function () {
						$(this).dialog("close");
					}
				}
			]
		});

		$('#alert-engaged-success').dialog({
			autoOpen: false,
			width: 400,
			modal: true,
			buttons: [
				{
					text: "Ok",
					click: function () {
						document.location.reload();
					}
				}
			]
		});

		$('#alert-disengaged-success').dialog({
			autoOpen: false,
			width: 400,
			modal: true,
			buttons: [
				{
					text: "Ok",
					click: function () {
						document.location.reload();
					}
				}
			]
		});
	});
</script>