<?php
$oHorse = Apps::getModel('Horse')->load($horseId);
$horse = $oHorse->getData();
//print_r($horse);
?>
<div class="col-md-12">
	<div class="panel panel-success">
		<a href="javascript:history.back()" class="pull-left"><b><i class="fa fa-arrow-circle-left "></i> Retour</b></a>
		<a href="javascript:void(0)" onclick="window.opener.location.reload();window.close()" class="pull-right"><b><i class="fa fa-refresh  "></i> Fermer et actualiser</b></a>
	</div>
	<div style="clear:both"></div>
</div>

<div class="col-md-12 course-content horse-detailed" style="margin-top: 20px">
	<div class="panel panel-success">
		<div class="panel-heading" style="padding: 5px 10px;">
			<h4 style="float:left;margin:0;font-size: 19px;"><?php echo $horse['name'] ?></h4>
			<span class="col-xs-7" style="font-size: 15px;color:#5f5e5e;">- <?php echo $horse['type'] ?> de <?php echo $horse['age'] ?> ans -</span>
			<div style="clear:both"></div>
		</div>
		<div class="panel-body">
			<ul class="col-xs-6" style="list-style: none;">
				<li>
					<span class="col-xs-7"><b>Specialisation :</b></span><span class="col-xs-5"><?php echo $oHorse->getSpecialization() ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Indice :</b></span><span class="col-xs-5"><?php echo $oHorse->getIndice() ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Réproduction :</b></span><span class="col-xs-5"><?php echo $oHorse->getIndiceReproduction() ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Robe :</b></span><span class="col-xs-5"><?php echo (is_null($horse['robe'])) ? '-' : $horse['robe']; ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Valeur :</b></span><span class="col-xs-5"><?php echo number_format($horse['price'], 0, '.', ' ') ?> <?php echo Text::__('turfoos') ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Gains :</b></span><span class="col-xs-5"><?php echo number_format($horse['gains'], 0, '.', ' ') ?> <?php echo Text::__('turfoos') ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Musique :</b></span><span class="col-xs-5"><?php echo $oHorse->get5LastPerfs($horse['sexe']) ?></span>
				</li>
			</ul>

			<ul class="col-xs-6" style="list-style: none;">
				<li>
					<span class="col-xs-7"><b>Père :</b></span>
					<span class="col-xs-5">
						<?php if($horse['father'] == 'Inconnu'){ ?>
							<?php echo $horse['father'] ?>
						<?php }else{ ?>
						<a href="javascript:void(0)" rel="<?php echo $horse['father_id'] ?>" class="horse-name"><?php echo $horse['father'] ?></a>
						<?php } ?>
					</span>
				</li>
				<li>
					<span class="col-xs-7"><b>Mère :</b></span>
					<span class="col-xs-5">
						<?php if($horse['mother'] == 'Inconnu'){ ?>
							<?php echo $horse['mother'] ?>
						<?php }else{ ?>
							<a href="javascript:void(0)" rel="<?php echo $horse['mother_id'] ?>" class="horse-name"><?php echo $horse['mother'] ?></a>
						<?php } ?>
					</span>
				</li>
				<li>
					<?php $fatherOfMotherData = $oHorse->getFatherOfMother() ?>
					<span class="col-xs-7"><b>Père de mère :</b></span>
					<span class="col-xs-5">
						<?php if($fatherOfMotherData == NULL){ ?>
							Inconnu
						<?php }else{ ?>
							<a href="javascript:void(0)" rel="<?php echo $fatherOfMotherData['id'] ?>>" class="horse-name"><?php echo $fatherOfMotherData['name'] ?></a>
						<?php } ?>
					</span>
				</li>
				<li>
					<span class="col-xs-7"><b>Propriètaire :</b></span><span class="col-xs-5"><?php echo $horse['proprio'] ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Entraineur :</b></span><span class="col-xs-5"><?php echo $horse['trainer'] ?></span>
				</li>
				<li>
					<span class="col-xs-7"><b>Eleveur :</b></span><span class="col-xs-5"><?php echo $horse['eleveur'] ?></span>
				</li>
			</ul>
		</div>
	</div>
</div>

<div class="col-md-12 course-content horse-detailed" style="margin-top: 20px">
	<div class="panel panel-success">
		<div class="panel-body"style="padding-left:11px;">
			<span class="col-md-12 fiche-cheval-sous-titre">Courses prévues</span>
		</div>
	</div>
</div>
<div class="col-md-12 horse-detailed">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs">
		<li class="active fiche-cheval-sous-titre"><a data-toggle="tab" href="#caracteres">Caractéristiques et Entrainements</a></li>
		<li class="fiche-cheval-sous-titre"><a data-toggle="tab" href="#courses">Courses</a></li>
		<li class="fiche-cheval-sous-titre"><a data-toggle="tab" href="#genetiques">Génétiques</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div id="caracteres" class="tab-pane fade in active" style="padding: 0 12px;">
			<script>
				var actual_fatigue, ecart_fatigue, add_fatigue, new_fatigue;
				var total_perf, previous_perf;
			</script>
			<div class="col-xs-2">&nbsp;</div><div class="col-xs-4">&nbsp;</div><div class="col-xs-1"></div><div class="col-xs-4 a-center"><b>Entrainement (15 heures réstants)</b></div><div class="col-xs-1">&nbsp;</div>
			<?php $perfKey = array(
					'trot' => array('_current', 600, '#0563ac', ''),
					'galop' => array('_current', 600, '#0563ac', ''),
					'endurance' => array('_current', 600, '#0563ac', ''),
					'vitesse' => array('_current', 600, '#0563ac', ''),
					'physique' => array('', 100, '#5aa445', '%'),
					'fatigue' => array('', 100, '#FF7FB6', '%')
				);
			?>
			<?php
			foreach($perfKey as $perf => $value){
				$disabled = 'false';
				if( ($horse['trot_base']== 0 && $perf == 'trot') ||($horse['galop_base']== 0 && $perf == 'galop') ){
					continue;
				}
				if($perf == 'physique'){
					if($horse[$perf . $value[0]] == 100){
						$disabled = 'true';
						$horse['training_' . $perf] = 0;
					}
				}
			?>
			<div class="row" style="margin-top: 10px">
				<span class="col-xs-2 ktr-title"><?php echo ucfirst($perf) ?></span>
				<div id="progressbar-<?php echo $perf ?>" class="col-xs-3 progressbar"></div>
				<span class="col-xs-2 perf-value current-<?php echo $perf ?>">
					<b><?php echo $horse[$perf . $value[0] ] ?><?php echo $value[3]?></b>
					<?php if($perf== 'physique'){ ?>
					<span>5%</span>
					<?php } ?>
					<input type="hidden" id="current-<?php echo $perf ?>-value" value="<?php echo $horse[$perf . $value[0] ] ?>"/>
				</span>
				<?php if($perf!= 'fatigue'){ ?>
				<div id="slider-<?php echo $perf ?>" class="col-xs-4 sliderbar"></div>
				<input type="text" disabled id="training-<?php echo $perf ?>" value="" size="1" class=" training-value"/>
				<?php } ?>
				<script type="text/javascript">
					var progressbar_<?php echo $perf ?> = $( "#progressbar-<?php echo $perf ?>" ).progressbar({value: <?php echo $horse[$perf . $value[0]] ?>, max: <?php echo $value[1] ?> }).find( ".ui-progressbar-value").css({"background": '<?php echo $value[2] ?>'});
					<?php if($perf!= 'fatigue'){ ?>
					var slider_<?php echo $perf ?> = $( "#slider-<?php echo $perf ?>" ).slider({disabled: <?php echo $disabled ?>, animate:true, range: "min", min: 0,max: 4, value:<?php echo $horse['training_' . $perf] ?>,
						slide: function( event, ui ) {
							$( "#training-<?php echo $perf ?>" ).val( ui.value );
						},change: function( event, ui ) {

							actual_fatigue = parseInt($('#current-fatigue-value').val());
							ecart_slider =  total_perf - previous_perf;
							add_fatigue = ecart_slider * 10;
							new_fatigue = actual_fatigue + add_fatigue;

							$( "#progressbar-fatigue").progressbar({value: new_fatigue});
							$('#current-fatigue-value').val(new_fatigue);

							//juste affichage
							if(new_fatigue < 0){
								new_fatigue = 0;
							}
							$('.current-fatigue b').html(new_fatigue + '%');

						},start: function( event, ui ) {
							previous_perf = parseInt($( "#slider-physique" ).slider( "value" )) + parseInt($( "#slider-vitesse" ).slider( "value" )) +  parseInt($( "#slider-endurance" ).slider( "value" )) ;
							<?php if($horse['galop_base']== 0){ ?>
							previous_perf+= parseInt($( "#slider-trot" ).slider( "value" ));
							<?php }else{ ?>
							previous_perf+= parseInt($( "#slider-galop" ).slider( "value" ));
							<?php } ?>
						},stop: function( event, ui ) {
							total_perf = parseInt($( "#slider-physique" ).slider( "value" )) + parseInt($( "#slider-vitesse" ).slider( "value" )) +  parseInt($( "#slider-endurance" ).slider( "value" )) ;
							<?php if($horse['galop_base']== 0){ ?>
							total_perf+= parseInt($( "#slider-trot" ).slider( "value" ));
							<?php }else{ ?>
							total_perf+= parseInt($( "#slider-galop" ).slider( "value" ));
							<?php } ?>
						}
					});
					$( "#training-<?php echo $perf ?>" ).val( $( "#slider-<?php echo $perf ?>" ).slider( "value" ) );
					<?php } ?>
				</script>
			</div>
			<?php
			}
			?>
			ajout bouton valider entrainement, test de 5max
		</div>
		<div id="courses" class="tab-pane fade" style="padding: 0 12px;">
			<h4>Messages Tab</h4>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>
		<div id="genetiques" class="tab-pane fade" style="padding: 0 12px;">
			<h4>Settings Tab</h4>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>
	</div>
</div>