<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Chéval :: créer :: <?php echo $data['name'] ?></h1>

        <!-- /.col-lg-12 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Informations primaires
            </div>
            <div class="panel-body">
                <div class="row">
                    <form role="form" method="post">
                        <input type="hidden" name="id" value="<?php echo $data['id'] ?>">
                        <div class="col-lg-6">

                            <div class="form-group input-group">
                                <span class="input-group-addon">Nom</span>
                                <input type="text" name="name" class="form-control" value="<?php echo $data['name'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Proprietaire</span>
                                <input type="text" name="proprio_id" class="form-control" value="<?php echo $data['proprio_id'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Entraineur</span>
                                <input type="text" name="trainer_id" class="form-control" value="<?php echo $data['trainer_id'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Eleveur</span>
                                <input type="text" name="eleveur_id" class="form-control" value="<?php echo $data['eleveur_id'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Age</span>
                                <input type="text" name="age" class="form-control" value="<?php echo $data['age'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Sexe</span>
                                <select class="form-control" name="sexe">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['sexe'] == 'M') ? 'selected="selected"' : ''; ?> value="M">Male</option>
                                    <option <?php echo ($data['sexe'] == 'F') ? 'selected="selected"' : ''; ?> value="F">Femele</option>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Qualité</span>
                                <input type="text" name="quality" class="form-control" value="<?php echo $data['quality'] ?>" />
                                <span class="input-group-addon">étoiles</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Qualité de reproduction</span>
                                <input type="text" name="quality_production" class="form-control" value="<?php echo $data['quality_production'] ?>" />
                                <span class="input-group-addon">étoiles</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Père</span>
                                <input type="text" name="father_id" class="form-control" value="<?php echo $data['father_id'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Mère</span>
                                <input type="text" name="mother_id" class="form-control" value="<?php echo $data['mother_id'] ?>" />
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon">Origine</span>
                                <input type="text" name="origine" class="form-control" value="<?php echo $data['origine'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Gains</span>
                                <input type="text" name="gains" class="form-control" value="<?php echo $data['gains'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Prix</span>
                                <input type="text" name="evaluation_price" class="form-control" value="<?php echo $data['evaluation_price'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Système</span>
                                <select class="form-control" name="is_system">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['is_system'] == '1') ? 'selected="selected"' : ''; ?> value="1">Oui</option>
                                    <option <?php echo ($data['is_system'] == '0') ? 'selected="selected"' : ''; ?> value="0">Non</option>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Qualification</span>
                                <select class="form-control" name="is_qualified">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['is_qualified'] == '1') ? 'selected="selected"' : ''; ?> value="1">Qualifié</option>
                                    <option <?php echo ($data['is_qualified'] == '0') ? 'selected="selected"' : ''; ?> value="0">Non Qualifié</option>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Type</span>
                                <select class="form-control" name="type">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['type'] == '0') ? 'selected="selected"' : ''; ?> value="0">Standard</option>
                                    <option <?php echo ($data['type'] == '1') ? 'selected="selected"' : ''; ?> value="1">- de 1 an</option>
                                    <option <?php echo ($data['type'] == '2') ? 'selected="selected"' : ''; ?> value="2">Etalons</option>
                                    <option <?php echo ($data['type'] == '3') ? 'selected="selected"' : ''; ?> value="3">Poulinières</option>
                                </select>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Status</span>
                                <select class="form-control" name="status">
                                    <option>--choisir--</option>
                                    <option <?php echo ($data['status'] == '1') ? 'selected="selected"' : ''; ?> value="1">Actif</option>
                                    <option <?php echo ($data['status'] == '0') ? 'selected="selected"' : ''; ?> value="0">Inactif</option>
                                </select>
                            </div>
                            <button class="btn btn-success" type="submit">Sauvegarder</button>
                            <button class="btn btn-danger" type="reset" onclick="history.back()">Annuler</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>
</div>


