<!-- DataTables JavaScript -->
<script src="/themes/admin/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="/themes/admin/bootstrap/datatables/dataTables.bootstrap.min.js"></script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Les chévaux</h1>
    </div>
    <!-- /.col-lg-12 -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button class="btn btn-primary btn-create-horse-manual" type="button">Création manuelle</button>
                    <button class="btn btn-primary btn-create-horse-auto" type="button">Création automatique</button>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-horse">
                            <thead>
                            <tr>
                                <th>ID#</th>
                                <th>Nom</th>
                                <th>Sexe/Age</th>
                                <th>Qual./Repr.</th>
                                <th>Propriétaire</th>
                                <th>Entraineur</th>
                                <th>Eleveur</th>
                                <th>Père</th>
                                <th>Mère</th>
                                <th>Prix</th>
                                <th>Type</th>
                                <th>Status</th>
                                <th>Système</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php  foreach($horses as $horse) { ?>
                                <tr class="">
                                    <td><?php echo $horse['id'] ?></td>
                                    <td><a href="/admin/horse/edit/id/<?php echo $horse['id'] ?>"><?php echo $horse['name'] ?></a></td>
                                    <td><?php echo $horse['sexe'] ?><?php echo $horse['age'] ?></td>
                                    <td><?php echo $horse['quality'] ?>/<?php echo $horse['quality_production'] ?></td>
                                    <td><?php echo $horse['proprio'] ?></td>
                                    <td><?php echo $horse['trainer'] ?></td>
                                    <td><?php echo $horse['eleveur'] ?></td>
                                    <td><?php echo $horse['father'] ?></td>
                                    <td><?php echo $horse['mother'] ?></td>
                                    <td><?php echo $horse['evaluation_price'] ?></td>
                                    <td><?php echo $horse['type'] ?></td>
                                    <td><?php echo $horse['status'] ?></td>
                                    <td><?php echo $horse['is_system'] ?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>


<script>
    $(document).ready(function() {
        $('#dataTables-horse').DataTable({
            responsive: true
        });
        $('.btn-create-horse-manual').click(function(){
            document.location.href= '/admin/horse/createmanual/'
        });
        $('.btn-create-horse-auto').click(function(){
            document.location.href= '/admin/horse/createauto/'
        });
    });
</script>