<?php

DEFINE( "USE_REWRITE_ENGINE", 1);
DEFINE( "OFFLINE_MODE", 0);

DEFINE( "SITE_URL", "http://www.turfoland.com/");

DEFINE('BEGINEER_GOLD', 5 );
DEFINE('BEGINEER_BANQUE', 300000 );
DEFINE('BEGINEER_LEVEL', 0);

DEFINE('DEF_STABLE_ID_YOUNG', 1);
DEFINE('DEF_STABLE_ID_4_5_6_ANS', 2);
DEFINE('DEF_STABLE_ID_7_8_9_ANS', 3);
DEFINE('DEF_STABLE_ID_10_ANS', 4);
DEFINE('DEF_STABLE_ID_OLD', 5);


DEFINE('RACE_GROUP_PARTICIPANT_MAX', 2);
