<?php

DEFINE( "USE_REWRITE_ENGINE", 1);
DEFINE( "OFFLINE_MODE", 0);

DEFINE( "SITE_URL", "http://www.turfoland.com/");

DEFINE('BEGINEER_GOLD', 5 );
DEFINE('BEGINEER_BANQUE', 300000 );
DEFINE('BEGINEER_LEVEL', 1);