<div>
	Niveau : plus il est élévé, plus vous auriez la chance de gagner un bon saillie lors de la vente
	<ul>
		<li>
			Niv 0 :<br>
			Avantages :
			<ul>
				<li>05 poulinières max</li>
			</ul>
			Qualification :
			<ul>
				<li>Il faut produire 10 poulains ou extension (payer 500 000) pour passer au prochain niveau</li>
			</ul>
		</li>
		<li>
			Niv 1 :<br>
			Avantages :
			<ul>
				<li>10 poulinières max</li>
			</ul>
			Qualification :
			<ul>
				<li>Il faut produire 50 poulains ou extension (payer 1 500 000) pour passer au prochain niveau</li>
			</ul>
		</li>
		<li>
			Niv 2 : <br>
			Avantages :
			<ul>
				<li>25 poulinières max</li>
				<li>1 étalon max</li>
			</ul>
			Qualification :
			<ul>
				<li>Il faut produire 100 poulains ou extension (payer 2 000 000) pour passer au prochain niveau</li>
			</ul>
		</li>
		<li>
			Niv 3
		</li>
	</ul>
</div>
<div>
	Vos Etalons<br>
	<ul>
		<li>
			Qualification :
			<ul>
				<li>être un male</li>
				<li>âge entre 5 à 25 ans</li>
				<li>avoir un ITR >= 120 </li>
			</ul>
		</li>
		<li>
			Niveau de réproduction de 1 à 5 selon l'ITR.
			<ul>
				<li>
					Classement de l'ITR :
					<ul>
						<li>ITR entre 170 et + évaluation élevage ------à 125 000 oros(approuvé)</li>
						<li>ITR entre 160 et 169 évaluation élevage ------à 75 000 oros(autorisé)</li>
						<li>ITR entre 150 et 159 évaluation élevage ------à 50 000 oros(autorisé)</li>
						<li>ITR entre 140 et 149 évaluation élevage ------à 25 000 oros(accepté)</li>
						<li>ITR entre 120 et 139 évaluation élevage ------à 12 500 oros(accepté)</li>
					</ul>
				</li>
				<li>
					Comment avoir l'ITR :<br>
					Il est calculé sur vos performance pendant un course. Il faut être placé pour avoir le point
					<ul>
						<li>1p : 10 points</li>
						<li>2p : 8 points</li>
						<li>3p : 5 points</li>
						<li>4p : 3 points</li>
						<li>5p : 1 point</li>
					</ul>
				</li>
			</ul>
		</li>
		<li>Héritage génétique</li>
	</ul>

	Vos poulinières<br>
	<ul>
		<li>
			Qualification :
			<ul>
				<li>être femelle</li>
				<li>âge entre 5 à 12 ans</li>
				<li>avoir un gain de 200 000 ou gagner une course : 1 fois (3ans) ou 2 fois(4ans) ou 3 fois (carière)</li>
			</ul>
		</li>
		<li>
			Niveau de réproduction de 1 à 5 selon le niveau réproducteur du père.<br>
			Mais on peut l'augmenter en fonction de votre ITR si supérieur à l'ITR du père<br>
			http://tpetrotteursfrancais.weebly.com/leacutelevage.html
		</li>
	</ul>

	Vos Poulains<br>
	<ul>
		<li>Vente entre Septembre et Novembre seulement (pour les 18 mois)</li>
	</ul>
</div>
<div>
	Affichage :
	<ul>
		<li>Liste de stock des saillies</li>
		<li>Liste de vos étalons</li>
		<li>Liste de vos poulinières</li>
		<li>Liste de vos poulains</li>
		<li>Liste de vos chevals entant qu'eleveur</li>
	</ul>
</div>