<?php
$sessionUser = Session::getUser();
$oStable = Apps::getModel('Stable');
$oStable->load($sessionUser['id']);
$stable = $oStable->getData();
$chevauxDeEcurie = $oStable->getHorsesForStable();
?>
<div class="col-lg-12">
	<h1><i class="fa fa-ticket"></i> Vos demandes des saillies réçus</h1>
	<?php //@todo: demande de saillie  ?>
</div>

<div class="col-lg-12">
	<h1><i class="fa fa-flask"></i> Saillies en stock</h1>
	<?php //@todo: saillie en stock  ?>
</div>

<div class="col-lg-12">
	<h1><i class="fa fa-mars"></i> Mes Etalons</h1>
	<div class="table-responsive">
		<?php
		$allHorsesBreedings = $oStable->getHorsesForStable(2);
		if(count($allHorsesBreedings) > 0 ){
			?>
			<table class="table">
				<thead>
				<tr>
					<th>Cheval</th>
					<th>Age/Sexe</th>
					<th>Père</th>
					<th>Père du mère</th>
					<th>Gains</th>
					<th>Repr.</th>
					<th>Saillies</th>
					<th>Prix</th>
					<th>Etat</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach( $allHorsesBreedings as $item) {
					$oHorse = Apps::getModel('Horse')->load($item['id']);
					$horse = $oHorse->getData();
					?>
					<tr>
						<td class="a-left">
							<?php echo $oHorse->getName($horse['name'], $horse['id'], $horse['status']) ?>
						</td>
						<td><?php echo $horse['sexe'] ?><?php echo $horse['age'] ?></td>
						<td><?php echo $oHorse->getName($horse['father'], $horse['father_id'], $horse['father_status']) ?></td>
						<td><?php echo $oHorse->getName($horse['father_mother'], $horse['father_mother_id'], $horse['father_mother_status']) ?></td>
						<td><?php echo number_format($horse['gains'], 0, '.', ' ') ?></td>
						<td><?php echo $oHorse->getIndiceReproduction() ?></td>
						<?php //@todo: nombre saillie, prix et etat  ?>
						<td><span style="color: #5aa445">14</span>/20</td>
						<td>10 000</td>
						<td>Enchère</td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
			<?php
		}else{
			echo "<div class='row'>Aucun étalon en votre possession</div>";
		}
		?>
	</div>
</div>

<div class="col-lg-12">
	<h1><i class="fa fa-venus"></i> Mes Poulinières</h1>
	<div class="table-responsive" style="overflow-x: visible;">
		<?php
		$allHorsesBreedings = $oStable->getHorsesForStable(3);
		if(count($allHorsesBreedings) > 0 ){
			?>
			<table class="table">
				<thead>
				<tr>
					<th>Cheval</th>
					<th>Age/Sexe</th>
					<th>Père</th>
					<th>Père du mère</th>
					<th>Gains</th>
					<th>Repr.</th>
					<th></th>
				</tr>
				</thead>
				<tbody>
				<?php foreach( $allHorsesBreedings as $item) {
					$oHorse = Apps::getModel('Horse')->load($item['id']);
					$horse = $oHorse->getData();
					?>
					<tr>
						<td class="a-left">
							<?php echo $oHorse->getName($horse['name'], $horse['id'], $horse['status']) ?>
						</td>
						<td><?php echo $horse['sexe'] ?><?php echo $horse['age'] ?></td>
						<td><?php echo $oHorse->getName($horse['father'], $horse['father_id'], $horse['father_status']) ?></td>
						<td><?php echo $oHorse->getName($horse['father_mother'], $horse['father_mother_id'], $horse['father_mother_status']) ?></td>
						<td><?php echo number_format($horse['gains'], 0, '.', ' ') ?></td>
						<td><?php echo $oHorse->getIndiceReproduction() ?></td>
						<td>
							<?php //@todo: faire saillir  ?>
							<div class="btn-group">
								<button data-toggle="dropdown" class="btn btn-default btn-xs dropdown-toggle" type="button" aria-expanded="true">
									Faire saillire
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu slidedown">
									<li><a href="">Saillie 1</a></li>
									<li><a href="">Saillie 2</a></li>
									<li><a href="">Saillie 1</a></li>
									<li><a href="">Saillie 1</a></li>
								</ul>
							</div>
						</td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
			<?php
		}else{
			echo "<div class='row'>Aucune poulinière en votre possession</div>";
		}
		?>
	</div>
</div>

<div class="col-lg-12">
	<h1><i class="fa fa-paw"></i> Mes Poulins et pouliches</h1>
	<div class="table-responsive">
		<?php
		$allHorsesBreedings = $oStable->getHorsesForStable(1);
		if(count($allHorsesBreedings) > 0 ){
			?>
			<table class="table">
				<thead>
				<tr>
					<th>Cheval</th><th>Age/Sexe</th><th>Père</th><th>Mère</th><th>Père du mère</th><th>Indice</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach( $allHorsesBreedings as $item) {
					$oHorse = Apps::getModel('Horse')->load($item['id']);
					$horse = $oHorse->getData();
					?>
					<tr>
						<td class="a-left">
							<?php echo $oHorse->getName($horse['name'], $horse['id'], $horse['status']) ?>
						</td>
						<td><?php echo $horse['sexe'] ?><?php echo $horse['age'] ?></td>
						<td><?php echo $oHorse->getName($horse['father'], $horse['father_id'], $horse['father_status']) ?></td>
						<td><?php echo $oHorse->getName($horse['mother'], $horse['mother_id'], $horse['mother_status']) ?></td>
						<td><?php echo $oHorse->getName($horse['father_mother'], $horse['father_mother_id'], $horse['father_mother_status']) ?></td>
						<td><?php echo $oHorse->getIndice() ?></td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
			<?php
		}else{
			echo "<div class='row'>Aucun poulain ou/et pouliche en votre possession</div>";
		}
		?>
	</div>
</div>

<div class="col-lg-12">
	<h1><i class="fa fa-sitemap"></i> Mes chévaux entant qu'éléveur</h1>
	<div class="table-responsive">
		<?php
		$allHorsesBreedings = $oStable->getAllHorsesBreedings();
		if(count($allHorsesBreedings) > 0 ){
			?>
			<table class="table">
				<thead>
				<tr>
					<th>Cheval</th><th>Age/Sexe</th><th>Père</th><th>Mère</th><th>Père du mère</th><th>Gains</th><th>Stat.</th><th>Indice</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach( $allHorsesBreedings as $item) {
					$oHorse = Apps::getModel('Horse')->load($item['id']);
					$horse = $oHorse->getData();
					?>
					<tr>
						<td class="a-left">
							<?php echo $oHorse->getName($horse['name'], $horse['id'], $horse['status']) ?>
						</td>
						<td><?php echo $horse['sexe'] ?><?php echo $horse['age'] ?></td>
						<td><?php echo $oHorse->getName($horse['father'], $horse['father_id'], $horse['father_status']) ?></td>
						<td><?php echo $oHorse->getName($horse['mother'], $horse['mother_id'], $horse['mother_status']) ?></td>
						<td><?php echo $oHorse->getName($horse['father_mother'], $horse['father_mother_id'], $horse['father_mother_status']) ?></td>
						<td><?php echo number_format($horse['gains'], 0, '.', ' ') ?></td>
						<td><?php echo $oHorse->getResultats() ?></td>
						<td><?php echo $oHorse->getIndice() ?></td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
			<?php
		}else{
			echo "<div class='row'>Aucun chévaux entant qu'éléveur</div>";
		}
		?>
	</div>
</div>

