<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Les écuries :: modifier :: Nouveau</h1>

        <!-- /.col-lg-12 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Informations de l'écurie
            </div>
            <div class="panel-body">
                <div class="row">
                    <form role="form" method="post">
                        <div class="col-lg-6">

                            <div class="form-group input-group">
                                <span class="input-group-addon">Ecurie</span>
                                <input type="text" name="name" class="form-control" value="<?php echo $post['name'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Nom (proprio)</span>
                                <input type="text" name="lastname" class="form-control" value="<?php echo $post['lastname'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Prénom (proprio)</span>
                                <input type="text" name="firstname" class="form-control" value="<?php echo $post['firstname'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Niveau</span>
                                <input type="text" name="level" class="form-control" value="<?php echo BEGINEER_LEVEL ?>" />
                                <span class="input-group-addon">étoiles</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Solde</span>
                                <input type="text" name="banque" class="form-control" value="<?php echo BEGINEER_BANQUE ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Gold</span>
                                <input type="text" name="gold" class="form-control" value="<?php echo BEGINEER_GOLD ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon">Email</span>
                                <input type="text" name="email" class="form-control" value="<?php echo $post['email'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Mot de passe</span>
                                <input type="password" name="password" class="form-control" value="<?php echo $post['password'] ?>" />
                            </div>
                            <button class="btn btn-success" type="submit">Sauvegarder</button>
                            <button class="btn btn-danger" type="reset" onclick="history.back()">Annuler</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>
</div>


