<!-- DataTables JavaScript -->
<script src="/themes/admin/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="/themes/admin/bootstrap/datatables/dataTables.bootstrap.min.js"></script>


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Les écuries :: modifier :: <?php echo $stable['name'] ?></h1>

        <!-- /.col-lg-12 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Informations de l'écurie
            </div>
            <div class="panel-body">
                <div class="row">
                    <form role="form" method="post">
                        <div class="col-lg-6">

                            <div class="form-group input-group">
                                <span class="input-group-addon">Ecurie</span>
                                <input type="text" name="name" class="form-control" value="<?php echo $stable['name'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Nom (proprio)</span>
                                <input type="text" name="lastname" class="form-control" value="<?php echo $stable['lastname'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Prénom (proprio)</span>
                                <input type="text" name="firstname" class="form-control" value="<?php echo $stable['firstname'] ?>" />
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Niveau</span>
                                <input type="text" name="level" class="form-control" value="<?php echo $stable['level'] ?>" />
                                <span class="input-group-addon">étoiles</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Solde</span>
                                <input type="text" name="banque" class="form-control" value="<?php echo $stable['banque'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">Gold</span>
                                <input type="text" name="gold" class="form-control" value="<?php echo $stable['gold'] ?>" />
                                <span class="input-group-addon">turfoos</span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group input-group">
                                <span class="input-group-addon">Email</span>
                                <input type="text" name="email" class="form-control" value="<?php echo $stable['email'] ?>" />
                            </div>
                            <button class="btn btn-success" type="submit">Sauvegarder</button>
                            <button class="btn btn-danger" type="reset" onclick="history.back()">Annuler</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                Les chevaux
            </div>
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-ecurie-cheval">
                        <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Qualité</th>
                            <th>Qualité production</th>
                            <th>Entraineur</th>
                            <th>Eleveur</th>
                            <th>Mère</th>
                            <th>Père</th>
                            <th>Âge</th>
                            <th>Sexe</th>
                            <th>Gains</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php  foreach($horses as $horse) { ?>
                            <tr class="">
                                <td><a href="/admin/stable/edit/id/<?php echo $horse['id'] ?>"><?php echo $horse['name'] ?></a></td>
                                <td><?php echo $stable['email'] ?></td>
                                <td><?php echo $stable['proprietaire'] ?></td>
                                <td class="center"><?php echo $stable['level'] ?></td>
                                <td class="center"><?php echo $stable['banque'] ?></td>
                                <td class="center"><?php echo $stable['last_activity'] ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#dataTables-ecurie-cheval').DataTable({
            responsive: true
        });
    });
</script>

